models/Product.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "product".
 *
 * @property integer $idProduct
 * @property string $name
 * @property string $description
 *
 * @property ProductAddress[] $productAddresses
 */
class Product extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'product';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name'], 'required'],
            [['description'], 'string'],
            [['name'], 'string', 'max' => 45],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'idProduct' => 'Id Product',
            'name' => 'Name',
            'description' => 'Description',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getProductAddresses()
    {
        return $this->hasMany(ProductAddress::className(), ['product_idProduct' => 'idProduct']);
    }
}

models/ProductForm.php
<?php

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

namespace app\models;

use Yii;
use yii;
/**
 * Description of ProductForm
 *
 * @author piotr
 */
class ProductForm extends Model{
    //put your code here
}

controllers/AddressController.php
<?php

/*
 */

namespace app\controllers;
use Yii;
use yii\web\Controller;
use app\models\ProductAddress;
use yii\data\ActiveDataProvider;

class AddressController extends Controller{
    
    public function actionList($id = null){
        
        if(!$id){
            $this->redirect(['product/list']);
        }
        
        $address = ProductAddress::findOne($id);
        $prices = null;
        if(!$address){
            $this->redirect(['product/list']);
        }
        $prices = $address->getProductPriceChanges();
        $dataProvider = new ActiveDataProvider([
            'query' => $prices
        ]);
        
        
        return $this->render('list', ['prices' => $dataProvider]);
        
    }
    
    public function actionAdd(){
        
    }
    
    public function actionView($id){
        return $this->actionList($id);
    }
}

controllers/ProductController.php
<?php

namespace app\controllers;

use Yii;
use yii\web\Controller;
use app\models\Product;
use yii\data\ActiveDataProvider;

class ProductController extends Controller{
    
    public function actionList($message = 'test'){
        
        $query = Product::find();
        
        $dataProvider = new ActiveDataProvider([
            'query' => $query,
            'pagination' => [
                'pageSize' => 10
            ]
        ]);
        
        
        return $this->render('list', [
            'dataProvider' => $dataProvider,
            
                ]);
    }
    
    public function actionAdd(){
        
        $product = new Product();
        
        if($product->load(Yii::$app->request->post()) && $product->validate()){
            $product->save();
        }
        
        return $this->render('add', ['productModel' => $product]);
    }
    
    public function actionView($id=null){
        
        if(!$id){
            return $this->redirect(['product/list']);
        }
        
        $product = Product::findOne($id);
        $addresses = new ActiveDataProvider(['query' => $product->getProductAddresses()]);
        $addressesSearch = new \app\models\ProductAddressSearch();
        return $this->render('view', ['productModel' => $product, 'addresses' => $addresses, 'addressesSearch' => $addressesSearch]);
    }
    
    public function actionUpdate($id){
        
        $product = Product::findOne($id);
        
        if($product->load(Yii::$app->request->post()) && $product->validate()){
            $product->save();
            return $this->redirect(['product/list']);
            
        }
        
        if($product){
            return $this->render('add', ['productModel' => $product]);
        }
        
        
    }
    
    public function actionDelete($id){
       
            $productToDelete = Product::findOne($id);
            
            if($productToDelete){
                
            $productToDelete->delete();
        }           
        
        
        return $this->redirect(['product/list']);
    }
    
}

views/product/_address.php
<?php
use yii\helpers\Html;
use yii\helpers\HtmlPurifier;
?>
<div>
fsd
</div>

views/product/add.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\widgets\Pjax;
/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

Pjax::begin([]);
$form = ActiveForm::begin([
    'id' => 'add-product',
    'options' => ['class' => 'form-horizontal', 'data' => ['pjax' => true]]
]) ?>

<?= $form->field($productModel, 'name'); ?>
<?= $form->field($productModel, 'description'); ?>

<?= Html::submitButton('Save product', ['class' => 'btn btn-primary']) ?>


<?php ActiveForm::end(); ?>
<?php Pjax::end(); ?>

views/product/list.php
<?php

use yii\helpers\Html;
use yii\widgets\LinkPager;
use yii\grid\GridView;
?>
<h1>Products list</h1>

<?php echo GridView::widget([
    'dataProvider' => $dataProvider,
    'columns' => [
        'name',
        'description',
        [
            'class' => 'yii\grid\ActionColumn',
            
        ]
        ]
    ]); ?>

views/product/view.php
<?php

use yii\helpers\Html;
use yii\widgets\LinkPager;
use yii\grid\GridView;
use yii\widgets\ListView;
use yii\widgets\DetailView
?>
<h1>Products details</h1>

<?=
DetailView::widget([
    'model' => $productModel,
    'attributes' => [
        'name',
        'description:html',
    ],
]);
?>
<hr>



<?=
GridView::widget([
    'dataProvider' => $addresses,
    'columns' => [
        'shopName',
        'regexp',
        'url',
        ['label' => 'Current price',
            'value' => function($data) {
                return $data->getProductPriceChanges()->orderBy(['date' => SORT_DESC] )->one()->value;
            }
        ],
        [
            'class' => yii\grid\ActionColumn::className(),
            'controller' => 'address',
        ],
    ]
]);
?>
<hr/>

<?= Html::a('Add Shop', ['/address/add'], ['class'=>'btn btn-primary']) ?>

erterter